// Auth schema is generated by the better-auth CLI and re-exported here.
// Run: pnpm dlx @better-auth/cli generate
// Then uncomment the line below:
// export * from "./auth";

// Add your own schema files and re-export them from this barrel, e.g.:
// export * from "./posts";
